### ISSUE TITLE
Create pre-commit hook

### ISSUE THREAD

**Issue by jag-k** [jag-k/pydantic-settings-export#4]
`pydantic-settings-export` must be available like pre-commit hook

Example of `.pre-commit-config.yml` in another project
```yml
# https://pre-commit.com/

default_stages: [ commit, push ]
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/jag-k/pydantic-settings-export
    rev: v1.0.0
    hooks:
      # Export a new config to README.md only
      - id: export
        args:
          - --path=README.md
          - --generator=region
      # Export settings with default config (from pyproject.toml)
      - id: export
```
